#!/bin/sh
# Fix up mount points device node names.
#
# /data needs to be mounted in initrd, but there is no udev that early,
# which means there is no /dev/block/platform/*/by-name/* (or bootdevice).
# This file is a map from the "by-name" path to /dev/mmcblkMpN.
# It also serves dhd to convert fstab and *.rc mount entries to systemd units,
# because at that boot stage there is still no udev "by-name" paths, even when
# systemd starts to execut the "*.mount" units.

DEVICE=$1
shift

echo "Fixing mount-points for device $DEVICE"

case "$DEVICE" in
        "sagit")
        sed -i \
            -e 's block/bootdevice/by-name/abl sde23 ' \
            -e 's block/bootdevice/by-name/ablbak sde24 ' \
            -e 's block/bootdevice/by-name/apdp sde5 ' \
            -e 's block/bootdevice/by-name/bk1 sda3 ' \
            -e 's block/bootdevice/by-name/bk2 sda4 ' \
            -e 's block/bootdevice/by-name/bk3 sda5 ' \
            -e 's block/bootdevice/by-name/bk31 sdd2 ' \
            -e 's block/bootdevice/by-name/bk32 sdd5 ' \
            -e 's block/bootdevice/by-name/bk4 sda8 ' \
            -e 's block/bootdevice/by-name/bk41 sde4 ' \
            -e 's block/bootdevice/by-name/bk42 sde30 ' \
            -e 's block/bootdevice/by-name/bk43 sde44 ' \
            -e 's block/bootdevice/by-name/bk5 sda12 ' \
            -e 's block/bootdevice/by-name/bk51 sdf2 ' \
            -e 's block/bootdevice/by-name/bk52 sdf3 ' \
            -e 's block/bootdevice/by-name/bk53 sdf6 ' \
            -e 's block/bootdevice/by-name/bk6 sda13 ' \
            -e 's block/bootdevice/by-name/bluetooth sde32 ' \
            -e 's block/bootdevice/by-name/boot sde40 ' \
            -e 's block/bootdevice/by-name/cache sda16 ' \
            -e 's block/bootdevice/by-name/cdt sdd3 ' \
            -e 's block/bootdevice/by-name/cmnlib sde19 ' \
            -e 's block/bootdevice/by-name/cmnlib64 sde21 ' \
            -e 's block/bootdevice/by-name/cmnlib64bak sde22 ' \
            -e 's block/bootdevice/by-name/cmnlibbak sde20 ' \
            -e 's block/bootdevice/by-name/cust sde42 ' \
            -e 's block/bootdevice/by-name/ddr sdd4 ' \
            -e 's block/bootdevice/by-name/devcfg sde7 ' \
            -e 's block/bootdevice/by-name/devcfgbak sde8 ' \
            -e 's block/bootdevice/by-name/devinfo sde35 ' \
            -e 's block/bootdevice/by-name/dip sde31 ' \
            -e 's block/bootdevice/by-name/dpo sde1 ' \
            -e 's block/bootdevice/by-name/dsp sde37 ' \
            -e 's block/bootdevice/by-name/frp sda7 ' \
            -e 's block/bootdevice/by-name/fsc sdf1 ' \
            -e 's block/bootdevice/by-name/fsg sde34 ' \
            -e 's block/bootdevice/by-name/hyp sde13 ' \
            -e 's block/bootdevice/by-name/hypbak sde14 ' \
            -e 's block/bootdevice/by-name/keymaster sde17 ' \
            -e 's block/bootdevice/by-name/keymasterbak sde18 ' \
            -e 's block/bootdevice/by-name/keystore sda6 ' \
            -e 's block/bootdevice/by-name/limits sde3 ' \
            -e 's block/bootdevice/by-name/logfs sda10 ' \
            -e 's block/bootdevice/by-name/logo sde36 ' \
            -e 's block/bootdevice/by-name/mdtp sde39 ' \
            -e 's block/bootdevice/by-name/mdtpsecapp sde25 ' \
            -e 's block/bootdevice/by-name/mdtpsecappbak sde26 ' \
            -e 's block/bootdevice/by-name/misc sda9 ' \
            -e 's block/bootdevice/by-name/modem sde41 ' \
            -e 's block/bootdevice/by-name/modemst1 sdf4 ' \
            -e 's block/bootdevice/by-name/modemst2 sdf5 ' \
            -e 's block/bootdevice/by-name/msadp sde6 ' \
            -e 's block/bootdevice/by-name/oops sda11 ' \
            -e 's block/bootdevice/by-name/persist sda14 ' \
            -e 's block/bootdevice/by-name/pmic sde9 ' \
            -e 's block/bootdevice/by-name/pmicbak sde10 ' \
            -e 's block/bootdevice/by-name/recovery sda15 ' \
            -e 's block/bootdevice/by-name/reserve sdd1 ' \
            -e 's block/bootdevice/by-name/rpm sde11 ' \
            -e 's block/bootdevice/by-name/rpmbak sde12 ' \
            -e 's block/bootdevice/by-name/sec sde2 ' \
            -e 's block/bootdevice/by-name/splash sde38 ' \
            -e 's block/bootdevice/by-name/ssd sda2 ' \
            -e 's block/bootdevice/by-name/sti sde33 ' \
            -e 's block/bootdevice/by-name/storsec sde28 ' \
            -e 's block/bootdevice/by-name/storsecbak sde29 ' \
            -e 's block/bootdevice/by-name/switch sda1 ' \
            -e 's block/bootdevice/by-name/system sde43 ' \
            -e 's block/bootdevice/by-name/toolsfv sde27 ' \
            -e 's block/bootdevice/by-name/tz sde15 ' \
            -e 's block/bootdevice/by-name/tzbak sde16 ' \
            -e 's block/bootdevice/by-name/userdata sda17 ' \
            -e 's block/bootdevice/by-name/xbl sdb1 ' \
            -e 's block/bootdevice/by-name/xblbak sdc1 ' \
            "$@"
        ;;
    *)
        cat <<EOF
****************************************************************
****************************************************************
ERROR: $DEVICE does not have mountpoint fixup data - see
       Sailfish OS HADK for details on how to fix this.
****************************************************************
****************************************************************
EOF
        exit 1
        ;;
esac

